export class ResponseFinanciacionUnificada {
  CODIGO: boolean;
  DESCRIPCION: string;
  MENSAJE: Array<Message>;
}

class Message {
  SALDO_CAPITAL_TOTAL_ADEUDADO: number;
  SALDO_CAPITAL_TOTAL_EN_TRAMITE: number;
  TOTAL_FINANCIACIONES_ACTIVAS_POSTPAGO: number;
  TOTAL_FINANCIACIONES_ACTIVAS_PREPAGO: number;
  TOTAL_FINANCIACIONES_ACTIVAS_REPOSICION: number;
  TOTAL_FINANCIACIONES_TECNOLOGIA_FIJO: number;
  TOTAL_FINANCIACIONES_TECNOLOGIA_MOVIL: number;
  TOTAL_FINANCIACIONES_TERMINAL_FIJO: number;
  TOTAL_FINANCIACIONES_TERMINAL_MOVIL: number;
  TOTAL_LINEAS_FINANCIADAS_ACTIVAS: number;
}
